/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author ZeekeR
 */
public class CustomerMainUI extends javax.swing.JFrame {

    /**
     * Creates new form customerslide
     */
    public CustomerMainUI() {
        initComponents();
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        repair = new javax.swing.JButton();
        sell = new javax.swing.JButton();
        buy = new javax.swing.JButton();
        back = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Welcome Customer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        repair.setIcon(new javax.swing.ImageIcon("C:\\Users\\malit\\OneDrive\\Desktop\\Work Place\\OOP Project\\oopproject\\src\\main\\java\\Backgrounds\\CustomerServiceButtion.png")); // NOI18N
        repair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        repair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repairActionPerformed(evt);
            }
        });
        jPanel1.add(repair, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 80, 320, 340));

        sell.setForeground(new java.awt.Color(255, 255, 255));
        sell.setIcon(new javax.swing.ImageIcon("C:\\Users\\malit\\OneDrive\\Desktop\\Work Place\\OOP Project\\oopproject\\src\\main\\java\\Backgrounds\\CustomerSellButtion.png")); // NOI18N
        sell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellActionPerformed(evt);
            }
        });
        jPanel1.add(sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 330, 340));

        buy.setForeground(new java.awt.Color(60, 63, 65));
        buy.setIcon(new javax.swing.ImageIcon("C:\\Users\\malit\\OneDrive\\Desktop\\Work Place\\OOP Project\\oopproject\\src\\main\\java\\Backgrounds\\CustomerBuyButtion.png")); // NOI18N
        buy.setBorder(new javax.swing.border.MatteBorder(null));
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });
        jPanel1.add(buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 340));

        back.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\malit\\OneDrive\\Desktop\\Work Place\\OOP Project\\oopproject\\src\\main\\java\\Backgrounds\\CustomerMainUI.jpg")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1040, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellActionPerformed
       CustomerSellUI m1 = new CustomerSellUI();
       m1.setVisible(true);
       this.hide();
        
        
    }//GEN-LAST:event_sellActionPerformed

    
    
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        LoginUI frm=new LoginUI();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        
        CustomerBuyingWaches m2 = new CustomerBuyingWaches();
        m2.setVisible(true);
        this.setVisible(false);
        

    }//GEN-LAST:event_buyActionPerformed

    private void repairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repairActionPerformed
        // TODO add your handling code here:
       
        CustomerRepairUI m1 = new CustomerRepairUI();
       m1.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_repairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMainUI().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton buy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton repair;
    private javax.swing.JButton sell;
    // End of variables declaration//GEN-END:variables
}
