/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.CustomerSellController;
import Models.CustomerSell;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ZeekeR
 */
public class CustomerSellUI extends javax.swing.JFrame {

    CustomerSell objCustomerSell;
    CustomerSellController objCustomerSellController;
    CustomerSell[] CustomerSellArray;
    ArrayList<CustomerSell> CustomerSellList;
    int index;
    
    public CustomerSellUI() {
        initComponents();
        objCustomerSellController = new CustomerSellController();
        CustomerSellArray = new CustomerSell[100];
        CustomerSellList = new ArrayList<>();
        index = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        txtSellModelID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSellDiscription = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Upload = new javax.swing.JButton();
        Done = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sell");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtSellModelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 300, 30));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Model");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 100, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Discription");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 160, 60));
        getContentPane().add(txtSellDiscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 300, 150));

        Back.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 90, 30));

        Upload.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Upload.setText("Upload");
        getContentPane().add(Upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        Done.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Done.setText("Done");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });
        getContentPane().add(Done, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 90, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Upload picture");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\malit\\OneDrive\\Desktop\\Work Place\\OOP Project\\oopproject\\src\\main\\java\\Backgrounds\\CustomerSellUI.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, 0, 1450, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        
        CustomerMainUI frm=new CustomerMainUI();
        frm.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BackActionPerformed

    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        // TODO add your handling code here:
        //display errror if have blank
        //storedata
        /*if(Sellmodel.getText().equals("")||Selldiscription.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter Data in to blankSpace");*/
        
        String ModelID = txtSellModelID.getText();
        String Description = txtSellDiscription.getText();
        
        

        objCustomerSell = objCustomerSellController.AddCustomerSell(ModelID, Description);
        boolean result = objCustomerSellController.insertCustomerSellTODB(objCustomerSell);
        CustomerSellArray[index] = objCustomerSell;
        CustomerSellList.add(objCustomerSell);
        index++;
    }//GEN-LAST:event_DoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerSellUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerSellUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerSellUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerSellUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerSellUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Done;
    private javax.swing.JButton Upload;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtSellDiscription;
    private javax.swing.JTextField txtSellModelID;
    // End of variables declaration//GEN-END:variables
}
